# Generated by Django 5.1.3 on 2024-11-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
