# Generated by Django 5.1.3 on 2024-11-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comprasRealizadas',
            field=models.IntegerField(default=0),
        ),
    ]
