# Generated by Django 5.1.3 on 2024-11-29 10:38

import Customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_coupon_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(default=Customer.models.default_expiration_date),
        ),
    ]
