# Generated by Django 5.1.3 on 2024-11-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_coupon_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_addres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
