# Generated by Django 5.1.3 on 2024-11-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('Delivery_Person', '0001_initial'),
        ('Order_Dispatcher', '0001_initial'),
        ('Order_Manager', '0001_initial'),
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Delivery_Person.delivery_person'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='order_dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_Dispatcher.order_dispatcher'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='order_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_Manager.order_manager'),
        ),
    ]
