# Generated by Django 5.1.3 on 2024-11-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidofooditem',
            name='food_item_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
