# Generated by Django 5.1.3 on 2024-11-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteData', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('unitPrice', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='restaurante',
            name='food_item',
            field=models.ManyToManyField(to='RestauranteData.fooditem'),
        ),
    ]
