# Generated by Django 5.1.3 on 2024-11-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteData', '0003_fooditem_restaurante_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='stockRestaurant',
            field=models.IntegerField(default=0),
        ),
    ]
