# Generated by Django 5.1.3 on 2024-11-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteData', '0005_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='cupons',
            field=models.BooleanField(default=False),
        ),
    ]
