# Generated by Django 5.1.3 on 2024-11-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteData', '0006_restaurante_cupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
