# Generated by Django 5.1.3 on 2024-11-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('customer', 'Customer'), ('menu_manager', 'Menu Manager'), ('delivery_person', 'Delivery Person'), ('order_manager', 'Order Manager'), ('order_dispatcher', 'Order Dispatcher')], default='customer', max_length=20),
        ),
    ]
