# Generated by Django 5.1.3 on 2024-11-28 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_baseuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este email ya esta registrado'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
